# yaml-language-server: $schema=https://raw.githubusercontent.com/omegabrr/omegabrr/refs/heads/main/config-schema.json
---
server:
  host: 0.0.0.0
  port: 7441
  apiToken: ""
schedule: "0 */6 * * *" # every 6th hour
clients:
  autobrr:
    host: http://localhost:7474
    apikey: API_KEY
  arr:
    - name: radarr
      type: radarr
      host: http://localhost:7878
      apikey: API_KEY
      filters:
        - 15 # Change me
      #matchRelease: false / true

    - name: radarr4k
      type: radarr
      host: http://localhost:7878
      apikey: API_KEY
      filters:
        - 16 # Change me
      #matchRelease: false / true

    - name: sonarr
      type: sonarr
      host: http://localhost:8989
      apikey: API_KEY
      filters:
        - 14 # Change me
      tagsInclude:
        - mytag
      tagsExclude:
        - myothertag
      #matchRelease: false / true

    - name: lidarr
      type: lidarr
      host: http://localhost:8686
      apikey: API_KEY
      filters:
        - 13 # Change me
      #matchRelease: false / true

    - name: readarr
      type: readarr
      host: http://localhost:8787
      apikey: API_KEY
      filters:
        - 12 # Change me
      #matchRelease: false # will not use other fields yet, so not needed.

    - name: whisparr
      type: whisparr
      host: http://localhost:6969
      apikey: API_KEY
      filters:
        - 69 # Change me
      matchRelease: true # needed as we grab site names

lists:
  - name: Latest TV Shows
    type: mdblist
    url: https://mdblist.com/lists/garycrawfordgc/latest-tv-shows/json
    filters:
      - 1 # Change me
  - name: Anticipated TV
    type: trakt
    url: https://api.autobrr.com/lists/trakt/anticipated-tv
    filters:
      - 22 # Change me

  - name: Upcoming Movies
    type: trakt
    url: https://api.autobrr.com/lists/trakt/upcoming-movies
    filters:
      - 21 # Change me

  - name: Upcoming Bluray
    type: trakt
    url: https://api.autobrr.com/lists/trakt/upcoming-bluray
    filters:
      - 24 # Change me

  - name: Popular TV
    type: trakt
    url: https://api.autobrr.com/lists/trakt/popular-tv
    filters:
      - 25 # Change me

  - name: StevenLu
    type: trakt
    url: https://api.autobrr.com/lists/stevenlu
    filters:
      - 23 # Change me

  - name: New Albums
    type: metacritic
    url: https://api.autobrr.com/lists/metacritic/new-albums
    filters:
      - 9 # Change me
  - name: Upcoming Albums
    type: metacritic
    url: https://api.autobrr.com/lists/metacritic/upcoming-albums
    filters:
      - 20 # Change me
